# Generated by Django 5.1.4 on 2025-03-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort_app', '0002_alter_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(),
        ),
    ]
